# Generated by Django 4.2 on 2023-04-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
                ('attribute', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=20000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('allow_allias', models.CharField(max_length=100)),
                ('super_allow_allias', models.CharField(max_length=100)),
                ('deny_allias', models.CharField(max_length=100)),
                ('allow_color', models.CharField(max_length=7)),
                ('deny_color', models.CharField(max_length=7)),
                ('super_allow_color', models.CharField(max_length=7)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('list_answers', models.ManyToManyField(to='main.question')),
                ('list_categories', models.ManyToManyField(to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('list_answers', models.ManyToManyField(through='main.Answer', to='main.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='id_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answers'),
        ),
        migrations.AddField(
            model_name='answer',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
